version: "3"

services:
  server:
    build: ./redundant-app-server
    restart: always
    ports:
      - "8000:8000"
  client:
    build: ./redundant--app-client
    ports:
      - "3000:3000"
    depends_on:
      - server
